name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No requirements file"

      - name: Run Unit Tests
        run: pytest || echo "No tests found"
